# Apache Cassandra Website config

# Site settings
title: Apache Cassandra Website
description: > # this means to ignore newlines until "baseurl:"
    The Apache Cassandra database is the right choice when you need scalability and high availability without
    compromising performance. Linear scalability and proven fault-tolerance on commodity hardware or cloud
    infrastructure make it the perfect platform for mission-critical data. Cassandra's support for replicating across
    multiple datacenters is best-in-class, providing lower latency for your users and the peace of mind of knowing that
    you can survive regional outages.
baseurl: ""
url: "http://cassandra.apache.org"
twitter_username: cassandra

destination: ../publish

exclude: [Makefile, README, Gemfile, Gemfile.lock, vendor]

include:
  - _images
  - .htaccess

gems:
  - jekyll-paginate-v2
  - jekyll-feed

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Pagination threshold for blog post listings
pagination:
  enabled: true
  per_page: 5
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
